# Generated by Django 2.0.6 on 2018-06-29 19:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('act_number', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('stop_date', models.DateField(blank=True, null=True)),
                ('term', models.CharField(blank=True, max_length=45, null=True)),
                ('payment', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'act',
            },
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id_cash', models.IntegerField(primary_key=True, serialize=False)),
                ('cash_date', models.DateField(blank=True, null=True)),
                ('sell', models.CharField(blank=True, max_length=45, null=True)),
                ('take', models.CharField(blank=True, max_length=45, null=True)),
                ('discount', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'cash',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orders_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_item', models.CharField(blank=True, max_length=45, null=True)),
                ('description_item', models.CharField(blank=True, max_length=45, null=True)),
                ('quality', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.CharField(blank=True, max_length=45, null=True)),
                ('act', models.ForeignKey(blank=True, db_column='act', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tenants_app.Act')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Rents',
            fields=[
                ('rents_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=45, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('stop_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rents',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('shelf_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shelf',
            },
        ),
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('tenants_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('telephone', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.AddField(
            model_name='rents',
            name='tenants',
            field=models.ForeignKey(db_column='tenants', on_delete=django.db.models.deletion.DO_NOTHING, to='tenants_app.Tenants'),
        ),
        migrations.AddField(
            model_name='cash',
            name='orders',
            field=models.ForeignKey(blank=True, db_column='orders', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tenants_app.Orders'),
        ),
        migrations.AddField(
            model_name='act',
            name='rents',
            field=models.ForeignKey(blank=True, db_column='rents', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tenants_app.Rents'),
        ),
        migrations.AddField(
            model_name='act',
            name='shelf',
            field=models.ForeignKey(blank=True, db_column='shelf', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tenants_app.Shelf'),
        ),
    ]
