# Generated by Django 2.0.6 on 2018-07-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenants',
            name='email',
            field=models.EmailField(blank=True, max_length=45, null=True),
        ),
    ]
