# Generated by Django 2.1.1 on 2018-11-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='cash_beznal',
            field=models.FloatField(default=0, max_length=45, verbose_name='Безналичный расчет'),
        ),
        migrations.AddField(
            model_name='cash',
            name='cash_nal',
            field=models.FloatField(default=0, max_length=45, verbose_name='Наличный расчет'),
        ),
    ]
