# Generated by Django 2.1.1 on 2018-12-03 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0002_auto_20181123_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер категории')),
                ('percent_from_sales', models.FloatField(default=0, max_length=5, verbose_name='Процент с продаж')),
                ('rent_of_shelf', models.BooleanField(default=True, verbose_name='Плата за аренду полки')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.AddField(
            model_name='act',
            name='category',
            field=models.ForeignKey(db_column='category', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tenants_app.Category', verbose_name='Категория условий аренды'),
            preserve_default=False,
        ),
    ]
