# Generated by Django 2.0.6 on 2018-08-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0002_auto_20180711_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenants',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenants',
            name='pass_given',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tenants',
            name='pass_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenants',
            name='pass_serial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
