# Generated by Django 2.0.6 on 2018-08-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0003_auto_20180807_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenants',
            old_name='email',
            new_name='E-mail',
        ),
        migrations.RenameField(
            model_name='tenants',
            old_name='address',
            new_name='Адрес',
        ),
        migrations.RenameField(
            model_name='tenants',
            old_name='pass_given',
            new_name='Выдан',
        ),
        migrations.RenameField(
            model_name='tenants',
            old_name='name',
            new_name='Имя',
        ),
        migrations.RenameField(
            model_name='tenants',
            old_name='telephone',
            new_name='Телефон',
        ),
        migrations.RemoveField(
            model_name='tenants',
            name='pass_number',
        ),
        migrations.RemoveField(
            model_name='tenants',
            name='pass_serial',
        ),
        migrations.AddField(
            model_name='tenants',
            name='Номер паспорта',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='tenants',
            name='Серия паспорта',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
