# Generated by Django 2.0.6 on 2018-08-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0004_auto_20180808_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenants',
            name='E-mail',
        ),
        migrations.RemoveField(
            model_name='tenants',
            name='Адрес',
        ),
        migrations.RemoveField(
            model_name='tenants',
            name='Выдан',
        ),
        migrations.RemoveField(
            model_name='tenants',
            name='Имя',
        ),
        migrations.RemoveField(
            model_name='tenants',
            name='Номер паспорта',
        ),
        migrations.RemoveField(
            model_name='tenants',
            name='Серия паспорта',
        ),
        migrations.RemoveField(
            model_name='tenants',
            name='Телефон',
        ),
        migrations.AddField(
            model_name='tenants',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='tenants',
            name='email',
            field=models.EmailField(blank=True, max_length=45, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='tenants',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='tenants',
            name='pass_given',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Выдан'),
        ),
        migrations.AddField(
            model_name='tenants',
            name='pass_number',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='tenants',
            name='pass_serial',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='tenants',
            name='telephone',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Телефон'),
        ),
    ]
