# Generated by Django 2.0.6 on 2018-08-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0006_auto_20180808_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='rents',
            options={'verbose_name': 'Rent', 'verbose_name_plural': 'Rents'},
        ),
        migrations.AlterModelOptions(
            name='tenants',
            options={'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
        migrations.AlterField(
            model_name='act',
            name='act_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
