# Generated by Django 2.0.6 on 2018-08-08 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0007_auto_20180808_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='act',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
