# Generated by Django 2.0.6 on 2018-08-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0008_auto_20180808_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='term_left',
            field=models.CharField(blank=True, editable=False, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='act',
            name='stop_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
