# Generated by Django 2.0.6 on 2018-08-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0009_auto_20180808_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
