# Generated by Django 2.0.6 on 2018-08-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0010_act_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='act',
            name='stop_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
