# Generated by Django 2.0.6 on 2018-08-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0011_auto_20180809_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='term',
            field=models.DateField(blank=True, editable=False, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='term_left',
            field=models.DateField(blank=True, editable=False, max_length=45, null=True),
        ),
    ]
