# Generated by Django 2.0.6 on 2018-08-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0012_auto_20180809_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='term',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='term_left',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
