# Generated by Django 2.0.6 on 2018-08-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0014_auto_20180809_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='rents',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='rents',
            name='term_left',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='rents',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
