# Generated by Django 2.0.6 on 2018-08-10 21:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0016_auto_20180809_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rents',
            name='number',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='rents',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата заключения'),
        ),
        migrations.AlterField(
            model_name='rents',
            name='stop_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата истечения'),
        ),
        migrations.AlterField(
            model_name='rents',
            name='tenants',
            field=models.ForeignKey(db_column='tenants', on_delete=django.db.models.deletion.DO_NOTHING, to='tenants_app.Tenants', verbose_name='Арендатор'),
        ),
    ]
