# Generated by Django 2.0.6 on 2018-08-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0017_auto_20180811_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
    ]
