# Generated by Django 2.0.6 on 2018-08-15 18:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0018_auto_20180815_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='act_number',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Номер акта'),
        ),
        migrations.AlterField(
            model_name='act',
            name='payment',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='act',
            name='rents',
            field=models.ForeignKey(blank=True, db_column='rents', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tenants_app.Rents', verbose_name='Арендатор'),
        ),
        migrations.AlterField(
            model_name='act',
            name='shelf',
            field=models.ForeignKey(blank=True, db_column='shelf', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tenants_app.Shelf', verbose_name='Полка'),
        ),
        migrations.AlterField(
            model_name='act',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата заключения'),
        ),
        migrations.AlterField(
            model_name='act',
            name='stop_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата истечения'),
        ),
    ]
