# Generated by Django 2.0.6 on 2018-08-16 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0020_auto_20180815_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rents',
            name='tenants',
            field=models.ForeignKey(db_column='tenants', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenants', to='tenants_app.Tenants', verbose_name='Арендатор'),
        ),
    ]
