# Generated by Django 2.0.6 on 2018-08-22 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0021_auto_20180816_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='stop_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата истечения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rents',
            name='stop_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата истечения'),
            preserve_default=False,
        ),
    ]
