# Generated by Django 2.0.6 on 2018-08-22 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0022_auto_20180822_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='rents',
            field=models.ForeignKey(db_column='rents', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tenants_app.Rents', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='act',
            name='shelf',
            field=models.ForeignKey(db_column='shelf', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tenants_app.Shelf', verbose_name='Полка'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='id_cash',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cash',
            name='orders',
            field=models.ForeignKey(db_column='orders', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tenants_app.Orders'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='act',
            field=models.ForeignKey(db_column='act', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tenants_app.Act'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='orders_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
