# Generated by Django 2.0.6 on 2018-08-22 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0023_auto_20180822_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='act',
            field=models.ForeignKey(db_column='act', on_delete=django.db.models.deletion.DO_NOTHING, to='tenants_app.Act', verbose_name='Номер акта'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='description_item',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name_item',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quality',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Количество'),
        ),
    ]
