# Generated by Django 2.0.6 on 2018-08-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0024_auto_20180822_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='materials',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='description_item',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
    ]
