# Generated by Django 2.0.6 on 2018-08-22 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0025_auto_20180822_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='orders',
            field=models.ForeignKey(db_column='orders', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tenants_app.Orders'),
        ),
    ]
