# Generated by Django 2.0.6 on 2018-08-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0027_auto_20180823_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='name',
            field=models.CharField(default=1, max_length=45, unique=True),
            preserve_default=False,
        ),
    ]
