# Generated by Django 2.0.6 on 2018-08-23 19:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0028_auto_20180823_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='cash_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата продажи'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='discount',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='orders',
            field=models.ForeignKey(db_column='orders', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tenants_app.Orders', verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='sell',
            field=models.CharField(default=0, max_length=45, verbose_name='Продано'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='take',
            field=models.CharField(default=0, max_length=45, verbose_name='Забрал арендатор'),
        ),
    ]
