# Generated by Django 2.0.6 on 2018-08-23 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0029_auto_20180823_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='act',
            field=models.OneToOneField(db_column='act', on_delete=django.db.models.deletion.DO_NOTHING, to='tenants_app.Act', verbose_name='Номер акта'),
        ),
    ]
