# Generated by Django 2.0.6 on 2018-08-26 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0031_auto_20180823_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='cash_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата продажи'),
        ),
    ]
