# Generated by Django 2.0.6 on 2018-08-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0032_auto_20180827_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='quality',
            field=models.CharField(default=0, max_length=45, verbose_name='Количество'),
        ),
    ]
