# Generated by Django 2.0.6 on 2018-08-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0033_auto_20180829_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='all_sell',
            field=models.CharField(default=0, max_length=45, verbose_name='Всего продано'),
        ),
        migrations.AddField(
            model_name='orders',
            name='all_take',
            field=models.CharField(default=0, max_length=45, verbose_name='Всего забрал арендатор'),
        ),
        migrations.AddField(
            model_name='orders',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
