# Generated by Django 2.0.6 on 2018-08-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0034_auto_20180829_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
