# Generated by Django 2.0.6 on 2018-09-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0035_auto_20180829_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenants',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='ФИО'),
        ),
    ]
