# Generated by Django 2.1.1 on 2018-09-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0036_auto_20180905_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='all_payment',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='payment',
            field=models.CharField(default=1, max_length=45, verbose_name='Оплата'),
            preserve_default=False,
        ),
    ]
