# Generated by Django 2.1.1 on 2018-09-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0038_auto_20180920_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='all_payment',
            field=models.CharField(default=models.CharField(max_length=45, verbose_name='Оплата'), max_length=45),
        ),
    ]
