# Generated by Django 2.1.1 on 2018-09-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0041_auto_20180920_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rents',
            name='stop_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата истечения'),
        ),
    ]
