# Generated by Django 2.1.1 on 2018-09-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0042_auto_20180926_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rents',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
