# Generated by Django 2.1.1 on 2018-09-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0043_auto_20180926_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='rents',
            name='is_break',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='rents',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
