# Generated by Django 2.1.1 on 2018-09-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0044_auto_20180926_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rents',
            name='is_break',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
