# Generated by Django 2.1.1 on 2018-09-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0045_auto_20180926_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='take',
        ),
    ]
