# Generated by Django 2.1.1 on 2018-10-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0047_auto_20180926_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='all_cash',
            field=models.CharField(default=0, max_length=45, verbose_name='Сумма продажи'),
        ),
    ]
